### ISSUE TITLE
Internal server error on threat_levels REST API

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#129]
while trying (on both dev and prod) to invoke `/api/v1/threat_levels` following error is returned:

```json
{
  "status": "500",
  "error": "Internal Server Error"
}
```

Inside production logs following error can be found:

```
F, [2016-08-09T08:56:23.955933 #22041] FATAL -- : 
NoMethodError (undefined method `id' for nil:NilClass):
  app/controllers/api/v1/threat_levels_controller.rb:51:in `block in scenarios_for_assessment'
  app/controllers/api/v1/threat_levels_controller.rb:47:in `scenarios_for_assessment'
  app/controllers/api/v1/threat_levels_controller.rb:41:in `block in threat_assessments_for_profile'
  app/controllers/api/v1/threat_levels_controller.rb:38:in `threat_assessments_for_profile'
  app/controllers/api/v1/threat_levels_controller.rb:31:in `threat_levels_for_profile'
  app/controllers/api/v1/threat_levels_controller.rb:25:in `block in threat_levels_for_profiles'
  app/controllers/api/v1/threat_levels_controller.rb:25:in `threat_levels_for_profiles'
  app/controllers/api/v1/threat_levels_controller.rb:21:in `threat_levels_data'
  app/controllers/api/v1/threat_levels_controller.rb:11:in `index'
```

**Comment by nowakowski** [comment]
This should be obviated by #133. @mkasztelnik - could you check whether this still occurs on dev?

**Comment by mkasztelnik** [comment]
This error is still thrown on dev. You can try it by going into https://dap.moc.ismop.edu.pl//api/v1/threat_levels?private_token=XXX page

**Comment by nowakowski** [comment]
@mkasztelnik That's the URL for prod. Are you sure you tested the right setup?

**Comment by mkasztelnik** [comment]
I was testing on both envs, on dev the result is the same.

**Comment by nowakowski** [comment]
@mkasztelnik OK, sorry. The error occurs because of the 94 `Result` objects in DAP none are linked to any `Scenario` and @tbartynski 's controller assumes that a `Result` will **always** have an assigned `Scenario`. This, in fact, seems like a sensible assumption - perhaps I should add a validation to ensure that `Result.scenario` is never `nil`?

Bottom line: the data is bogus. I can either link each existing `Result` to an arbitrary (random) `Scenario` or delete all `Result` objects from the DB. Which is it?

**Comment by mkasztelnik** [comment]
I propose to keep it clean and delete absolute data, but we need to be sure that this data is not used by "porownywaczka" - ping @mpawlik

**Comment by mpawlik** [comment]
I think we can drop old results, @tbartynski correct me if I'm wrong:)

**Comment by nowakowski** [comment]
Just to be clear - I will drop all `Result` objects but leave their parent `ThreatAssessment` and `Scenario` objects intact. Is this OK?

**Comment by nowakowski** [comment]
Should be fixed now (please verify).

**Comment by tbartynski** [comment]
I think I should change the controller. It is possible for porównywaczka to produce results without associated scenarios in case when porównywaczka was not able to match to any existing scenario. No match is also a result in my opinion so it is stored in DAP to indicate that the computation was completed.

**Comment by nowakowski** [comment]
We had a chat with @tbartynski regarding this issue. From the database design standpoint, creating null `Result` object to denote that no matching scenario has been found is absolutely awful, bordering on criminal - for starters, it breaks 2NF because "lack of applicable scenarios" is **not** a property of the `Result` entity and does not follow from any of its candidate keys. I know they came up with this crap fifty years ago, but the rules exist for a reason... ;)

Rather than what @tbartynski proposes, the corresponding status can be easily stored in the DB by extending `ThreatAssessment` with an enum flag (e.g. `status`) and assigning an appropriate value (e.g. `no_matching_scenarios_found`) when the run is a failure. I can add the necessary logic in DAP if you want.

**Comment by nowakowski** [comment]
Sorry, misclick.

**Comment by mkasztelnik** [comment]
I propose to use status only for threat assessment state, thus `new`, `running`, `finished`, `error` values should be enough. If status is `finished` and no results are assigned to run than we know that no scenarios were matched.

**Comment by tbartynski** [comment]
#140 describes the solution on the DAP side.
I'll enhance the hyperflow executor to support it.
I'll close this issue once the two issues above are fixed.

**Comment by nowakowski** [comment]
#140 already deployed on dev.

**Comment by tbartynski** [comment]
Pull request https://github.com/mpawlik/hyperflow-amqp-executor/pull/2 waiting for @mpawlik review.

**Comment by mpawlik** [comment]
I'm not sure how I feel about proposed changes, it seems that the model is trying to closely follow minor implementation details of execution engine. We already have ThreatAssessmentRun's status, why do we need another status in ThreatAssessment? Isn't it easier to just handle ThreatAssessments with no results?

**Comment by mkasztelnik** [comment]
I was discussing the same with @tbartynski. He explains that `ThreatAssessmentRun` is something which is started and is active for a long time. In defined time interval it triggers `ThreatAssessment` execution. Right now we don't have information about status of single `ThreatAssessment`. That is the reason for introducing mentioned `status`. 

Use case from UI: without status we don't know if `ThreatAssesment` we are presenting is finished or it is in the process of calculation.

**Comment by mpawlik** [comment]
@mkasztelnik @tbartynski it's not how it works. Lifetime of 'running' state for both entities is almost the same. It seems that we're doing the 'creep function from one entity to other' thing again.

ThreatAssessmentRun represents calculation of ThreatAssessments for multiple profiles. Threat Assessment's sole purpose was to group profile->best matching scenarios (aka Results). In current setup ThreatAssessmentRun and ThreatAssessmens are created by Hypgen in the exact same function. When all ThreatAssessments are calculated (this may result in creating Results) Hypgen updates the ThreatAssessmentRun's status. This happens almost instantaneously, if calculations are complete you'll now about this reading either entity's field. So in case of detecting the 'finished' state of calculations, there is no clear benefit of knowing this per ThreatAssessment.

Do we need to know the status of each individual ThreatAssessment, as if we would check for errors? I'm not convinced, because at this point it's impossible to get a meaningful error out of 'porownywaczka', while ThreatAssessmentRun's error means that something went wrong while creating computing setup or with HyperFlow. If the 'state' field is added to ThreatAssessment, this opens up a whole new dimension of handling exceptions. How should we interpret a situation, when one ThretAssessment completes, and ThreatAssessmentRun fails? Should we ignore other ThreatAssessments and say 'those are all results we got, and they are good'? Should we mark the whole batch as 'failed'? etc.

How to solve the problem presented in the use case: Check if ThreatAssessment's ThreatAssessmentRun has a 'finished' state. ThreatAssessmentRun contains the start and end date of calculations, so it's most probably being accessed already.

**Comment by mkasztelnik** [comment]
Ok that is totally different scenario than @tbartynski described us last Wednesday.

**Comment by tbartynski** [comment]
@mpawlik I believed that we also used Threat Assessment Run to model a continuous monitoring of profile (more specifically a set of periodically computed assessments). We don't do that at all? If not then I'm sorry for misleading everyone.
Anyway, Threat Assessment status is implemented in both DAP and hyperflow-amqp-executor and knowing status of partial computation is better than knowing status of a set of computations.
@mpawlik exception handling is simple, I just check the exit code of comparing so there is no more effort needed other than reviewing my pull request.

**Comment by mpawlik** [comment]
@tbartynski I think we cleared up things a bit in f2f conversation. Did changes proposed in this issue made it to master? If so we can close this issue.
