### ISSUE TITLE
Add profile name and populate it with correct names

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#180]
Profile object does not have `name` fields right now. As a results on the UI we are showing internal id on the UI - this is not user friendly for the end users (at least for DK). Please add `name` field to `Profile` and populate it with correct values.

This issue blocks https://github.com/ismop/dap/issues/179

**Comment by bwilk** [comment]
@nowakowski could you provide us with specification of profile_id/shape/location to "profile name" mapping ?

**Comment by nowakowski** [comment]
I'll try to get this done by Monday.

**Comment by nowakowski** [comment]
Done and pushed to prod. New attribute is called `Profile.name`. Syntax is:

- For neosentio profiles: `Profil neosentio: <ID assigned by Daniel Kessler>`
- For budokop profiles: `Profil budokop: <internal DB ID>` (Budokop profiles have no external ID)

Updated API, specs and docs.

@mkasztelnik Please close this ticket if satisfied.

**Comment by dharezlak** [comment]
The prefixes `Profil neosentio` and `Profil budokop` are not necessary here. We already know the vendor by looking at the vendors property. Also, it makes internationalization more difficult. This is a minor but I would fix it to minimize future UI hard coded commits to parse the name.

**Comment by mkasztelnik** [comment]
Looks good and it is already used by eitwid.

**Comment by nowakowski** [comment]
Reopening due to comment by @dharezlak .

My intent was to provide a human-readable name. If I truncate this to, say, `42`, this may lead to confusion further down the line (i.e. a couple months from now when we all forget what this attribute means and why it was added). I can rewrite the names but I would advise against it. If you insist, please specify what you consider to be the "proper" syntax for the `name` field.

**Comment by mkasztelnik** [comment]
Right now I propose to leave it at it is and let user test the new behavior.

**Comment by dharezlak** [comment]
OK, closing.
