### ISSUE TITLE
Add name and description into Scenario 

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#55]
These fields will be used on UI

**Comment by mkasztelnik** [comment]
It seems like `Scenario` model has a lot of outdated fields and relations, in my opinion following elements can be removed:

  * file_name
  * payload
  * context_id
  * profile_type_id
  * thread_level

/cc @dharezlak, @bwilk, @tbartynski

**Comment by tbartynski** [comment]
I think we can get rid of file_name and payload since we there will be appropriate timelines with measurements so there will also be an association with experiment and devices (or device aggregations) and it will be possible to traverse to profile via devices. If that is true we can remove existing fields.

Regarding thread_level if we get as assessment for a scenario we should associate Scenario with a ThreatAssement object.

I definitely think that we should remove all field that we are not using now since it's relatively easy to add them once we need them and unused fields introduce a lot of confusion.
