### ISSUE TITLE
Measurements exported as CSV

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#74]
It is requested by ISMOP team to download sensor values as CSV. The open questions are as follow:

1. in which rest API it should be added (sensors or measurements)
2. what format should be used (especially when measurements from many sensors should be exported)
3. should it be synchronous or asynchronous proces?

Any comments remarks are welcomed. This can also simplify the work @tbartynski and @mpawlik are doing with scenario matching tool since they are converting data from json into CSV. 

see https://github.com/ismop/eitwid/issues/45 for rationale. 

/cc @dharezlak

**Comment by nowakowski** [comment]
@mkasztelnik Could you specify who exactly is the requestor?

**Comment by mkasztelnik** [comment]
Prof. Lesniak's team and dr. Borecka.

**Comment by nowakowski** [comment]
Thanks.

**Comment by nowakowski** [comment]
I guess the most pressing issue is item 2, i.e. the export format. Since Prof. Leśniak's team will be consuming this data, I would like to ask them to provide a suitable template (or a set of examples) showing how they wish this data to be formatted.

**Comment by mkasztelnik** [comment]
This is nice article http://www.krisquigley.co.uk/2015/12/08/polling-for-file-generation.html presenting how file generation can be done in the background and how such files can be presented to end user.

**Comment by mkasztelnik** [comment]
@nowakowski, @bwilk any deadline when this feature will be implemented?

**Comment by nowakowski** [comment]
@mkasztelnik On 18 Dec I sent out invitations to all members of Professor Leśniak's team to contribute to this discussion by clarifying their requirements. As there has been no reply I assume it's not a priority issue for them. I will proceed once I obtain specific information on what is to be done.

**Comment by kszostek** [comment]
1. Both. Not only for tests of our team, but also for different analysis in future.
2. I believe that the CSV format presented you before might be the target of the export. But the best approach would be to create a simple export editor: what columns, what order, how to separate files, etc. 
3. Async. A zip file containing selected exports is prepared on the server, user gets email with the link once it's ready.

**Comment by nowakowski** [comment]
@kszostek Could you attach a sample CSV file to this discussion? Note that we cannot index measurements by timestamp because - unlike in simulated data - there is no guarantee that a full set of real measurements will be available for any arbitrary timestamp.
I will leave @mkasztelnik to comment on the editor feature mentioned in item 2. Granted, it would probably be "the best approach" in terms of flexibility and feature richness but I'm not so sure about the cost/benefit tradeoff involved here. We need to consider the workload involved.
Btw., it is likely that the export could be a near-real-time operation in which case we don't need to complicate matters by turning it into an asynchronous process (I could be eating my words a month from now ;).

**Comment by kszostek** [comment]
If no real measurements is available for a particular timestamp, an empty value should be returned.

I think any file format would be ok as far as it contains timestamp and values or empty strings for NULLs. 

It can be like this - it's just like the file I've received lately:
X,Y,Z,type,temp,ppres,Timestamp,Name
-40,20,19,1,6.55618306,,1435755600,Tout_13
-40,20,19,1,6.54645702,,1435756500,Tout_13
-40,20,19,1,6.90271642,,1435757400,Tout_13
-40,20,19,1,6.62428802,,1435758300,Tout_13
-40,20,19,1,6.90074565,,1435759200,Tout_13

[Tout13 - example.txt](https://github.com/ismop/dap/files/77617/Tout13.-.example.txt)

**Comment by mkasztelnik** [comment]
We agreed during UI presentation that 2 kind of import actions will be available:
  1. every chart will have export button where what is presented on chart will be exported (see https://github.com/ismop/eitwid/issues/45)
  2. there will be `export experiment data button` available for finished experiments (see https://github.com/ismop/eitwid/issues/58)

This is what we will do for now. After this is implemented and we will have free resources we can discuss about further improvements, e.g. editor (chart export is a kind of editor IMHO). 

/cc @dharezlak

**Comment by bwilk** [comment]
Let's talk about exporting experiments first. The aforementioned export format may be unsuitable for our data model. In the format you've mentioned timestamp plays a role of indexing column - for each timestamp should be present a valid measurement for all parameters at a sensor location (XYZ). In our model we simply get measurements with a timestamp of the reading. Therefore, there is no way to produce a list of timeastamps that can group readings, in order to compose a row. Assuming this I propose to further discuss the output format. The two possible solutions coming to my mind are:

Solution 1:

timestamp, X, Y, Z, param_id, value
1435755600, -40, 20, 19, id123, 6.23,
1435755600, -40, 21, 19, id124, 6.21,
1435755601, -41, 20, 23, id432, 5.23,

This is a raw list of values orderred by timestamp - each row represents single measurement. All the sensors are mixed in this format. 

Solution 2:

timestamp, param_id, value, 
1435755600, id123, 6.23,
1435755600, id124, 6.21,
1435755601, id432, 5.23,

A file for a single X, Y, Z point, or a delimited (e.g. vertical line to separate points) section of a file. Sorted by timestamp. Parameters and values mixed. 

Solution 3:

id123 - timestamp, id123 - value, id124 - timestamp, id124 - value, id125 - timestamp, id125 - value, 
1435755600, 6.23,     1435755600, 6.23,     1435755600, 6.23, 
1435755601, 6.21,     1435755601, 6.21,     1435755602, 6.21, 
1435755602, 5.23,     1435755602, 5.23,     1435755603, 5.23,

A file for a single X, Y, Z point, or a delimited (e.g. vertical line to separate points) section of a file. Ids in headers, pairs of timestamp - value, columns.

**Comment by bwilk** [comment]
Prof. Leśniak's team please comment on that. Preferences and suggestions are welcomed.

**Comment by ChuchroM** [comment]
We prefer first or second solution. First solution is similar to export data from Flac models. But ask Bartosz Baliś . He is programming an aplication, which will manage cleaning, comparision and anomaly detection programs. The purpose of the application is, inter alia, the transfer of data in the appropriate format, length and time resolution.

**Comment by mkasztelnik** [comment]
@bwilk any progress?

**Comment by bwilk** [comment]
Yes. It's implemented and merged from "csv" to "master" branch. Waiting for development instance to have it tested on the real data.

**Comment by mkasztelnik** [comment]
@bwilk export capability is added into charts where Chart Presenter is used and for Experiment. For simple experiment (10 days period) timeout occurred. 

You can test it using ui-dev installation.

Remarks:
  * export speed should be improved. If it is not possible than we need to move it into background process (this will require changes in dap and eitwid)
  * CSV file names should be customized. E.g. `experiment-#{experiment.name}.csv`, `chart-1.2.3-2015.01.01.13:40-2015.01.03.12:00.csv`

**Comment by bwilk** [comment]
Feature is ready
