### ISSUE TITLE
Add possibility to ask about oldest reading for concrete parameter timeline

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#83]
Rationale: https://github.com/ismop/eitwid/issues/70

**Comment by nowakowski** [comment]
@mkasztelnik @dharezlak A worker has been created which periodically polls all timelines for earliest measurements and updates two new fields which have been added to the Timeline model (`timeline.earliest_measurement_timestamp` and `timeline.earliest_measurement_value`). Since this is a computationally-intensive operation it will only be performed once per day (configurable interval). The new fields are duly returned by `GET /timelines`.

Deployed to dap-dev. Please try it out and give me :+1: when you feel it's OK to deploy this to production.

**Comment by mkasztelnik** [comment]
:+1:

**Comment by mkasztelnik** [comment]
Please let me know when this will be deployed into prod.

**Comment by nowakowski** [comment]
@mkasztelnik Done.
